version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    env_file:
      - .env
    environment:
      - MAIL_USER = ${MAIL_USER}
      - MAIL_PASSWORD = ${MAIL_PASSWORD}
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - sns_network
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db_contaienr
    env_file:
      - .env
    ports:
      - "3006:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sns_network

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: frontend_container
    working_dir: /app
    volumes:
      -  ./src/frontend:/app
      -  ./src/public:/app/dist
    networks:
      - sns_network

networks:
 sns_network:
  driver: bridge

volumes:
  db_data:


    
  