version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    env_file:
      - .env
    environment:
      - MAIL_USER = ${MAIL_USER}
      - MAIL_PASSWORD = ${MAIL_PASSWORD}
    ports:
      - 3001:9000
    working_dir: /app 
    volumes:
      - ./:/app
    networks:
      - sns_network
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db_container
    env_file:
      - .env
    ports:
      - "3006:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Docker/db/my.cnf:/etc/mysql/my.cnf
    networks:
      - sns_network

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: frontend_container
    volumes:
      -  ./src/frontend:/app
      -  ./src/public:/app/dist
    networks:
      - sns_network
    ports:
      - 3000:3000
    command: npm run dev

networks:
 sns_network:
  driver: bridge

volumes:
  db_data:


    
  
