server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;


     # 静的ファイル（.js, .css, .pngなど）は直接返す
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg|eot|mp4|webp)$ {
        try_files $uri =404;
        access_log off;
        expires max;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php_container:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        #try_files $uri $uri/ /index.php?path=$uri&$args;
    
    }

    location ~ /\.ht {
        deny all;
    }
}